### ISSUE TITLE
Plugins with angular-cli

### ISSUE THREAD

**Issue by zszep** [willsoto/ng-chartist#105]
Can't get any plugin working with angular-cli. Is there any working sample out there that would shed some light on this. I added ` chartist.min.js and chartist-plugin-pointlabels.js` inside the script tag section of angluar-cli and the following inside the component:
import * as Chartist from 'chartist';

and for the options:

```
 this.options = {
            fullWidth: true,
            showArea: false,
            showLine: true,
            low: 0,
            chartPadding: {
                right: 40
            },
            axisX: {
                showLabel: true
            },
            axisY: {
                showLabel: true
            },
            plugins: [
                Chartist.plugins.ctPointLabels({
                    textAnchor: 'middle'
                })
            ]
        };
```

But I am getting this error: Uncaught (in promise): TypeError: Cannot read property 'ctPointLabels' of undefined

**Comment by willsoto** [comment]
Sounds like you have another error. Can you paste the entire config?

**Comment by zszep** [comment]
The html:
```
<div class="ct-chart ct-square">
    <x-chartist
    [data]="data"
    [type]="type"
    [options]="options">
    </x-chartist>
</div>
```
And the ts file:

```
import { Component } from '@angular/core';
import { StatistikaService } from '../statistika.service';
import { ToasterService } from 'angular2-toaster';
import * as Chartist from 'chartist';

declare var legend: any;

@Component({
    selector: 'statistika-stacionar-cmp',
    templateUrl: './statistika-stacionar.component.html',
    styleUrls: ['./statistika-stacionar.component.css']
})
export class StatistikaStacionarComponent {

    type = 'Line';
    options: any;


    data: any = {};

    constructor(private _statistikaService: StatistikaService,
        private _toasterService: ToasterService) {
        this.getStacionarDataByMonth();

        this.options = {
            fullWidth: true,
            showArea: false,
            showLine: true,
            low: 0,
            chartPadding: {
                right: 40
            },
            axisX: {
                showLabel: true
            },
            axisY: {
                showLabel: true
            },
            plugins: [
                Chartist.plugins.ctPointLabels({
                   textAnchor: 'middle'
                }),
            ]
        };

    }

    getStacionarDataByMonth() {
        this._statistikaService.getStacionarDataByMonth()
            .then((data: any) => {
                let fdata = data
                    .filter(stacionar => stacionar.djelatnost.startsWith('AIL'))
                    .map(function (obj) {
                        let pad = '00';
                        obj.yearMonth = '' + obj.month;
                        obj.yearMonth = pad.substring(0, pad.length - obj.yearMonth.length) + obj.yearMonth;
                        obj.yearMonth = obj.yearMonth + '/' + obj.year;
                        return obj;
                    });
                let xAxis = fdata.map(function (obj) {
                    return obj.yearMonth;
                });
                let dts = fdata.map(function (obj) {
                    return obj.dTSKoeficijent;
                });
                let brojRacuna = fdata.map(function (obj) {
                    return obj.brojRacuna;
                });
                let fakturiraniIznos = fdata.map(function (obj) {
                    return obj.ukupno / 100000;
                })
                this.data = {
                    'labels': xAxis,
                    'series': [dts, brojRacuna, fakturiraniIznos]
                };
            })
            .catch(err => { this._toasterService.pop('error', 'Greška pri učitavanju podataka', err); });
    }
}
```
The runtime error:
```
core.es5.js:1084 ERROR Error: Uncaught (in promise): TypeError: Cannot read property 'ctPointLabels' of undefined
TypeError: Cannot read property 'ctPointLabels' of undefined
    at new StatistikaStacionarComponent (http://localhost:8080/main.bundle.js:2873:66)
    at createClass (http://localhost:8080/vendor.bundle.js:11002:26)
    at createDirectiveInstance (http://localhost:8080/vendor.bundle.js:10838:37)
    at createViewNodes (http://localhost:8080/vendor.bundle.js:12188:49)
    at createRootView (http://localhost:8080/vendor.bundle.js:12093:5)
    at callWithDebugContext (http://localhost:8080/vendor.bundle.js:13224:42)
    at Object.debugCreateRootView [as createRootView] (http://localhost:8080/vendor.bundle.js:12685:12)
    at ComponentFactory_.create (http://localhost:8080/vendor.bundle.js:10029:46)
    at ComponentFactoryBoundToModule.create (http://localhost:8080/vendor.bundle.js:3638:29)
    at ViewContainerRef_.createComponent (http://localhost:8080/vendor.bundle.js:10229:62)
    at RouterOutlet.activateWith (http://localhost:8080/vendor.bundle.js:38862:40)
    at ActivateRoutes.placeComponentIntoOutlet (http://localhost:8080/vendor.bundle.js:38043:16)
    at ActivateRoutes.activateRoutes (http://localhost:8080/vendor.bundle.js:38024:26)
    at http://localhost:8080/vendor.bundle.js:37960:58
    at Array.forEach (native)
    at new StatistikaStacionarComponent (http://localhost:8080/main.bundle.js:2873:66)
    at createClass (http://localhost:8080/vendor.bundle.js:11002:26)
    at createDirectiveInstance (http://localhost:8080/vendor.bundle.js:10838:37)
    at createViewNodes (http://localhost:8080/vendor.bundle.js:12188:49)
    at createRootView (http://localhost:8080/vendor.bundle.js:12093:5)
    at callWithDebugContext (http://localhost:8080/vendor.bundle.js:13224:42)
    at Object.debugCreateRootView [as createRootView] (http://localhost:8080/vendor.bundle.js:12685:12)
    at ComponentFactory_.create (http://localhost:8080/vendor.bundle.js:10029:46)
    at ComponentFactoryBoundToModule.create (http://localhost:8080/vendor.bundle.js:3638:29)
    at ViewContainerRef_.createComponent (http://localhost:8080/vendor.bundle.js:10229:62)
    at RouterOutlet.activateWith (http://localhost:8080/vendor.bundle.js:38862:40)
    at ActivateRoutes.placeComponentIntoOutlet (http://localhost:8080/vendor.bundle.js:38043:16)
    at ActivateRoutes.activateRoutes (http://localhost:8080/vendor.bundle.js:38024:26)
    at http://localhost:8080/vendor.bundle.js:37960:58
    at Array.forEach (native)
    at resolvePromise (http://localhost:8080/polyfills.bundle.js:7076:31) [angular]
    at resolvePromise (http://localhost:8080/polyfills.bundle.js:7047:17) [angular]
    at http://localhost:8080/polyfills.bundle.js:7124:17 [angular]
    at Object.onInvokeTask (http://localhost:8080/vendor.bundle.js:4327:37) [angular]
    at ZoneDelegate.invokeTask (http://localhost:8080/polyfills.bundle.js:6761:36) [angular]
    at Zone.runTask (http://localhost:8080/polyfills.bundle.js:6529:47) [<root> => angular]
    at drainMicroTaskQueue (http://localhost:8080/polyfills.bundle.js:6957:35) [<root>]
    at HTMLAnchorElement.ZoneTask.invoke (http://localhost:8080/polyfills.bundle.js:6828:25) [<root>]
```

**Comment by willsoto** [comment]
Did you load the CtPointLabels plugin at all? If it is a plugin that attaches itself to `Chartist.plugins`, then I would expect it to be loaded somewhere after Chartist

**Comment by zszep** [comment]
I loaded via the angular-cli.json config file in the scripts sections of the file:

  ```
"scripts": [
        "../node_modules/jquery/dist/jquery.min.js",
        "../node_modules/moment/min/moment.min.js",
        "../node_modules/tinymce/tinymce.min.js",
        "../node_modules/tinymce/themes/modern/theme.min.js",
        "../node_modules/tinymce/plugins/link/plugin.min.js",
        "../node_modules/tinymce/plugins/paste/plugin.min.js",
        "../node_modules/tinymce/plugins/table/plugin.min.js",
        "../node_modules/tinymce/plugins/lists/plugin.min.js",
        "../node_modules/tinymce/plugins/advlist/plugin.min.js",
        "../node_modules/tinymce/plugins/print/plugin.min.js",
        "../node_modules/tinymce/plugins/preview/plugin.min.js",
        "../node_modules/tinymce/plugins/media/plugin.min.js",
        "../node_modules/signalr/jquery.signalR.min.js",

        "../node_modules/chartist/dist/chartist.min.js",
        "../node_modules/chartist-plugin-pointlabels/dist/chartist-plugin-pointlabels.js"
      ],
```

**Comment by zszep** [comment]
If I do a console.log(Chartist.plugins) I get 'undefined'. I suppose it is somehow missing in the typedef file.

**Comment by willsoto** [comment]
I feel like this issue should be filed against https://github.com/gionkunz/chartist-plugin-pointlabels. I'm not doing anything here (afaik) that would prevent plugins from loading.

**Comment by zszep** [comment]
I can do a console.log(Chartist) and I get the object back. Inspecting the logged object, the plugins array  is obviously missing,

**Comment by zszep** [comment]
Can you propose a plugin you know is working, so I can try it out?

**Comment by willsoto** [comment]
Unfortunately not, sorry.

**Comment by willsoto** [comment]
Let me know if this is a bug on my end and I will reopen.
